Update update-all

diff --git a/update-all b/update-all
--- a/update-all
+++ b/update-all
@@ -14,12 +14,9 @@ function error {
 #Checking Update:
 echo -e "\e[31mChecking for updates...\e[0m"
 echo -e "\e[32mUpdates are found! \e[0m"
-# Prompt:
-echo "Please enter your password to start updating"
-echo -en '\n'
 # Main:
-sudo apt autoremove -y && sudo apt --fix-broken install && sudo apt update --fix-missing || error '\e[31mUnable to update, please check your internet connection...\e[0m' && sudo apt upgrade -y && sudo apt dist-upgrade -y && sudo apt full-upgrade -y && sudo apt autoremove -y
-echo -en && sudo apt install -f && sudo rm -rf /var/lib/dpkg/info/*.postinst && sudo dpkg --configure -a
+apt autoremove -y && apt --fix-broken install && apt update --fix-missing || error '\e[31mUnable to update, please check your internet connection...\e[0m' && apt upgrade -y && apt autoremove -y
+echo -en && sudo apt install -f
 #Comment 'clear' below to stop clearing the output:
 clear -x
 # Ending:
